# Generated by Django 6.0.3 on 2026-04-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=10000)),
                ('category', models.CharField(choices=[('electronics', 'Electronic Devices'), ('stationary', 'Stationaries'), ('wallet', 'Wallets'), ('card', 'Cards'), ('bottle', 'Water Bottles'), ('bag', 'Bags'), ('key', 'Keys'), ('umbrella', 'Umbrellas'), ('keychain', 'Keychains'), ('clothes', 'Clothes'), ('shoes', 'Shoes'), ('accessory', 'Accessories'), ('other', 'Other Items')], max_length=100)),
            ],
        ),
    ]
