# Generated by Django 6.0.3 on 2026-04-18 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def location_categories(apps, schema_editor):
    MMULocation = apps.get_model('items', 'MMULocation')

    LOCATIONS = [
        ('fci', 'FCI Building'),
        ('fom', 'FOM Building'),
        ('faie', 'FAIE Building'),
        ('fcm', 'FCM Building'),
        ('clc', 'CLC'),
        ('mph', 'MPH / Annex Hall'),
        ('misri-plaza', 'Misri Plaza'),
        ('rimbun-ilmu', 'Rimbun Ilmu'),
        ('dtc', 'DTC'),
        ('chancelery', 'MMU Chancelery'),
        ('stad', 'STAD Building'),
        ('ips', 'IPS Building'),
        ('library', 'Library'),
        ('bakery', 'Bakery'),
        ('haji-tapah', 'Haji Tapah'),
        ('starbees', 'Starbees'),
        ('dapo-sahang', 'Dapo Sahang'),
        ('hb1', 'Hostel Block 1'),
        ('hb2', 'Hostel Block 2'),
        ('hb3', 'Hostel Block 3'),
        ('hb4', 'Hostel Block 4'),
        ('entrance-A', 'MMU Entrance A'),
        ('entrance-B', 'MMU Entrance B'),
        ('bustop-A', 'Bustop Entrance A'),
        ('bustop-B', 'Bustop Entrance B'),
        ('cyberpark', 'MMU Cyberpark'),
        ('stadium', 'Stadium MMU'),
        ('isc', 'Indoor Sports Centre'),
        ('footbal', 'Football Field'),
        ('rugby', 'Rugby Field'),
        ('swimming', 'Swimming Pool'),
        ('tennis', 'Tennis Court'),
        ('basketball', 'Basketball Court'),
        ('volleyball', 'Volleyball Court'),
        ('archery', 'Archery'),
        ('edc', "EDC Building"),
        ('fmd', 'FMD Building'),
        ('masjid', 'Masjid'),
        ('nea', 'NEA'),
        ('eaa', 'EAA'),
        ('eab', 'EAB'),
        ('guest house', 'MMU Guest House'),
    ]

    for code, name in LOCATIONS:
        MMULocation.objects.update_or_create(
            location_code = code, 
            defaults = {'location_name': name}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MMULocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=50, unique=True)),
                ('location_name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')])),
                ('post_datetime', models.DateTimeField()),
                ('post_itemcategory', models.CharField(choices=[('electronics', 'Electronic Devices'), ('stationary', 'Stationaries'), ('wallet', 'Wallets'), ('card', 'Cards'), ('bottle', 'Water Bottles'), ('bag', 'Bags'), ('key', 'Keys'), ('umbrella', 'Umbrellas'), ('keychain', 'Keychains'), ('clothes', 'Clothes'), ('shoes', 'Shoes'), ('accessory', 'Accessories'), ('other', 'Other Items')], max_length=100)),
                ('post_description', models.TextField()),
                ('post_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.mmulocation')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),

        migrations.RunPython(location_categories),
    ]
