# Generated by Django 6.0.3 on 2026-05-05 15:01

from django.db import migrations

def location_categories(apps, schema_editor):
    MMULocation = apps.get_model('items', 'MMULocation')

    LOCATIONS = [
        ('fci', 'FCI Building'),
        ('fom', 'FOM Building'),
        ('faie', 'FAIE Building'),
        ('fcm', 'FCM Building'),
        ('clc', 'CLC'),
        ('mph', 'MPH / Annex Hall'),
        ('misri-plaza', 'Misri Plaza'),
        ('rimbun-ilmu', 'Rimbun Ilmu'),
        ('dtc', 'Dewan Tun Canselor'),
        ('chancellery', 'MMU Chancellery'),
        ('stad', 'STAD Building'),
        ('ips', 'IPS / ERU'),
        ('library', 'Library'),
        ('bakery', 'Bakery'),
        ('haji-tapah', 'Haji Tapah'),
        ('deen', 'Deens Cafe'),
        ('starbee', 'Starbee'),
        ('dapo-sahang', 'Dapo Sahang'),
        ('hb1', 'Hostel HB1'),
        ('hb2', 'Hostel HB2'),
        ('hb3', 'Hostel HB3'),
        ('hb4', 'Hostel HB4'),
        ('entrance-A', 'MMU Entrance A'),
        ('entrance-B', 'MMU Entrance B'),
        ('bustop-A', 'Bustop Entrance A'),
        ('bustop-B', 'Bustop Entrance B'),
        ('cyberpark', 'MMU Cyberpark'),
        ('stadium', 'MMU Stadium'),
        ('isc', 'Indoor Sports Centre'),
        ('footbal', 'Football Field'),
        ('rugby', 'Rugby Field'),
        ('swimming', 'Swimming Pool'),
        ('tennis', 'Tennis Court'),
        ('basketball', 'Basketball Court'),
        ('badminton', 'Badminton Court'),
        ('volleyball', 'Volleyball Court'),
        ('archery', 'Archery'),
        ('edc', "Entrepreneurship Developement Center (EDC)"),
        ('fmd', 'Facilities Management Department (FMD)'),
        ('mosque', 'Mosque'),
        ('nea', 'Non Executive Apartment (NEA)'),
        ('eaa', 'Executive Apartment A (EAA)'),
        ('eab', 'Executive Apartment B (EAB)'),
        ('guest house', 'MMU Guest House'),
    ]

    for code, name in LOCATIONS:
        MMULocation.objects.update_or_create(
            location_code = code, 
            defaults = {'location_name': name}
        )

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(location_categories),
    ]