# Generated by Django 6.0.3 on 2026-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_mmulocation_post_delete_itemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='userposts_images/'),
        ),
    ]
