# Generated by Django 6.0.3 on 2026-06-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_post_post_image_alter_post_post_itemcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('returned', 'Returned')], default='open', max_length=20),
        ),
    ]
