# Generated by Django 6.0.3 on 2026-05-06 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.mmulocation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10),
        ),
    ]
