# Generated by Django 6.0.4 on 2026-05-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_userreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
