# Generated by Django 6.0.3 on 2026-05-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_feedback_post_alter_feedback_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('is_reported', models.BooleanField(default=False)),
            ],
        ),
    ]
