# Generated by Django 6.0.4 on 2026-05-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_report_post_alter_report_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Waiting for Reverify', 'Waiting for Reverify'), ('Verified', 'Verified'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
