# Generated by Django 6.0.3 on 2026-05-09 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
