# Generated by Django 6.0.3 on 2026-04-30 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MMULocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(max_length=50, unique=True)),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('post_datetime', models.DateTimeField()),
                ('post_itemcategory', models.CharField(choices=[('electronics', 'Electronic Devices'), ('stationary', 'Stationaries'), ('wallet', 'Wallets'), ('card', 'Cards'), ('bottle', 'Water Bottles'), ('bag', 'Bags'), ('key', 'Keys'), ('umbrella', 'Umbrellas'), ('keychain', 'Keychains'), ('clothes', 'Clothes'), ('shoes', 'Shoes'), ('accessory', 'Accessories'), ('other', 'Other Items')], max_length=100)),
                ('post_description', models.TextField()),
                ('post_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.mmulocation')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
