# Generated by Django 6.0.3 on 2026-05-01 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_itemcategory',
            field=models.CharField(choices=[('electronics', 'Electronic Devices'), ('stationery', 'Stationaries'), ('wallet', 'Wallets'), ('card', 'Cards'), ('bottle', 'Water Bottles'), ('bag', 'Bags'), ('key', 'Keys'), ('umbrella', 'Umbrellas'), ('keychain', 'Keychains'), ('clothes', 'Clothes'), ('shoes', 'Shoes'), ('accessory', 'Accessories'), ('other', 'Other Items')], max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.mmulocation'),
        ),
    ]
