# Generated by Django 6.0.3 on 2026-04-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_bio_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_mmu_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='mmu_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mmu_proof',
            field=models.ImageField(blank=True, null=True, upload_to='mmu_proof/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='submitted_for_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
