# Generated by Django 6.0.3 on 2026-05-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_is_mmu_verified_profile_mmu_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_mmu_verified',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mmu_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mmu_proof',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='submitted_for_verification',
        ),
    ]
