# Generated by Django 6.0.3 on 2026-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
