# Generated by Django 6.0.3 on 2026-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_is_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='need_reverify',
            field=models.BooleanField(default=False),
        ),
    ]
