# Generated by Django 6.0.4 on 2026-05-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_need_reverify'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_reverified',
            field=models.BooleanField(default=True),
        ),
    ]
