# Generated by Django 6.0.3 on 2026-04-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BUG', 'System Bug'), ('USER', 'Non-MMU User'), ('POST', 'Inappropriate Post')], max_length=10)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('details', models.TextField()),
                ('is_checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.post')),
            ],
        ),
    ]
