# Generated by Django 6.0.3 on 2026-04-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_image/'),
        ),
    ]
