# Generated by Django 6.0.3 on 2026-05-01 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_userreport_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReport',
        ),
    ]
